In [1]:
%who

Interactive namespace is empty.


In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.24.3


In [4]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\ASUSVivaBook\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\asusvivabook\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>

In [5]:
li_list = [1, 2.0, 3]
li_list

[1, 2.0, 3]

In [6]:
type(li_list[1])

float

In [7]:
np.array([1,2,3])

array([1, 2, 3])

Numpy'ın içindeki her veri kesinlikle aynı tipte olmalıdır.

In [8]:
["ali", 1]

['ali', 1]

In [9]:
np.array(["ali", 1])

array(['ali', '1'], dtype='<U11')

İkisini de stringe çevirdi. Çünkü ikisi de aynı tipte olmalı.
Bu neden önemli?
Elimizdeki bir veri setiyle işlem yapacaksak öncesinde o veri setinin her bir kodunun, sütununun veri tipini analiz etmeden işleme geçersek analiz error verebilir.

In [10]:
np_array = np.array([1,2,3])

In [11]:
np_array.shape

(3,)

In [12]:
np_array.resize(5,3)

In [14]:
np_array.shape

(5, 3)

In [15]:
%who

li_list	 np	 np_array	 


%who ile hangi değişkenlerimizin olduğuna bakıyoruz.

In [19]:
arr_1D_int = np.array([1,2,3])
print(arr_1D_int.dtype)
print("Bytes:", arr_1D_int.itemsize)

arr_1D_float = np.array([1,2,3], dtype=np.float64)
print(arr_1D_float.dtype)
print("Bytes:", arr_1D_float.itemsize)

int32
Bytes: 4
float64
Bytes: 8


Numpy'ın en temel özelliği öncesinden belirlediğimiz veri tipini sabit tutmasıdır.

In [21]:
np.ones((3, 2), dtype=np.int64)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [23]:
np.zeros((3, 2), dtype=np.int64)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Repeat özelliği numpy'da herhangi bir listedeki veya array'daki değişkenin ne kadar tekrar edebileceğini gösterir.

In [25]:
np.repeat([1,2,3],6)

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])

Arange fonksiyonu belli sayı aralığında liste oluşturur.

In [27]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [31]:
np_lin = np.linspace(1,20,10)

Argmax o arraydeki maksimum değeri verir. Hatta maksimum değerden ziyade maksimum değerin olduğu indeksi verir.

In [32]:
np_lin.argmax()

9

In [37]:
np_lin.argmax?

Docstring:
a.argmax(axis=None, out=None, *, keepdims=False)

Return indices of the maximum values along the given axis.

Refer to `numpy.argmax` for full documentation.

See Also
--------
numpy.argmax : equivalent function
Type:      builtin_function_or_method

In [39]:
a = np.arange(10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a[::2]

array([0, 2, 4, 6, 8])

hstack ve vstack özellikle iki farklı array'i, numpy objesini birleştirmek için kullanılır.

In [43]:
npa_p = np.ones([2,3], int)

In [44]:
npa_p

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
2*npa_p

array([[2, 2, 2],
       [2, 2, 2]])

In [46]:
np.vstack([npa_p, 2*npa_p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [47]:
np.hstack([npa_p, 15*npa_p, 10*npa_p])

array([[ 1,  1,  1, 15, 15, 15, 10, 10, 10],
       [ 1,  1,  1, 15, 15, 15, 10, 10, 10]])

Farklı kaynaklardan gelen verileri:
vstack, alt alta birleştiriyor;
hstack, yan yana birleştiriyor.

In [50]:
import sys

li_Demo = list(range(1000))
print(type(li_Demo))
print("Bytes:")
print(sys.getsizeof(1)*len(li_Demo))

print()
print("Bytes:")
arr_Demo = np.arange(1000)
print(arr_Demo.size*arr_Demo.itemsize)

<class 'list'>
Bytes:
28000

Bytes:
4000


In [52]:
import time

c_Size = 10000000

li_1 = list(range(c_Size))
li_2 = list(range(c_Size))

arr_1 = np.arange(c_Size)
arr_2 = np.arange(c_Size)

start = time.time()

li_3 = [(x+y) for x,y in zip(li_1,li_2)]
print("Listede toplam:", (time.time()-start)*1000, "ms")

start = time.time()

arr_3 = arr_1+arr_2
print("Arrayde toplam:", (time.time()-start)*1000, "ms")

Listede toplam: 692.1417713165283 ms
Arrayde toplam: 8.91423225402832 ms


In [53]:
# matematiksel işlemler kolay

arr_x = np.array([1,2,3])
arr_y = np.array([4,5,6])

print("x:", arr_x)
print("y:", arr_y)
print("x+y:", arr_x + arr_y) #toplama [1 2 3] + [4 5 6] = [5 7 9]
print("x-y:", arr_x - arr_y) #çıkarma [1 2 3] - [4 5 6] = [-3 -3 -3]
print("x*y:", arr_x * arr_y) #çarpma [1 2 3] * [4 5 6] = [4 10 18]
print("x/y:", arr_x / arr_y) #bölme [1 2 3] / [4 5 6] = [0.25 0.4 0.5]
print("x^2:", arr_x**2) #üst [1 2 3] ^2 = [1 4 9]

x: [1 2 3]
y: [4 5 6]
x+y: [5 7 9]
x-y: [-3 -3 -3]
x*y: [ 4 10 18]
x/y: [0.25 0.4  0.5 ]
x^2: [1 4 9]


In [54]:
np.array([1,2,3]).ndim

1

In [58]:
np.array([[1,2,4], [1,2,3]])

array([[1, 2, 4],
       [1, 2, 3]])

In [61]:
np.array([[[1,2,4]], [[1,2,3]]]).ndim

3

In [62]:
np.array([[[1,2,4]], [[1,2,3]]]).shape

(2, 1, 3)

In [63]:
np.array([[1,2], [1,2], [1,2]]).shape 

# ilk sonuç kaç array olduğu, 
# sonraki sayı her bir array'in içindekini göstermiş olur 
# en sondaki en son array'in içeriğini gösterir.

(3, 2)

In [64]:
np.array([[[1,2,4]], [[1,2,3]]]).shape

(2, 1, 3)

In [67]:
np.array([[[1,2,4]], [[1,2,3]]]).reshape(2,3)
# array'in iç içe geçişliliğini değiştirmiş oldu.

array([[1, 2, 4],
       [1, 2, 3]])

In [69]:
np_array_32 = np.array([[1,2], [1,2], [1,2]])

In [70]:
np_array_23 = np.array([[1,2], [1,2], [1,2]]).reshape(2,3)

In [71]:
np_array_32

array([[1, 2],
       [1, 2],
       [1, 2]])

In [72]:
np_array_23

array([[1, 2, 1],
       [2, 1, 2]])

In [73]:
np_array_32.ravel()
# hepsini tek seviyeye getiriyor.

array([1, 2, 1, 2, 1, 2])

In [75]:
np_array_32.reshape(6,1)

array([[1],
       [2],
       [1],
       [2],
       [1],
       [2]])

In [77]:
np.sort(np_array_32.reshape(6,1), axis =1)

array([[1],
       [2],
       [1],
       [2],
       [1],
       [2]])

In [80]:
np_array_32 > 1
# 1'den büyük olanlar gelir

array([[False,  True],
       [False,  True],
       [False,  True]])

In [81]:
np_array_32 > 2

array([[False, False],
       [False, False],
       [False, False]])

In [82]:
np_array_32[np_array_32 > 1]
# mantıksal işleme denk gelen elemanaları bize geri dönüş yapmış olur. 

array([2, 2, 2])

In [84]:
arr_orders = np.array([
    [2, 0, 0, 0],
    [4, 1, 2, 2],
    [0, 1, 0, 1],
    [6, 0, 1, 2]
])
arr_totals = np.array([3, 20.50, 10, 14.25])
arr_prices = np.linalg.solve(arr_orders, arr_totals)
arr_prices

# orderlar ve total var. Burada Numpy yardımıyla siparişlerin 
# ücretleri ne kadar onu göreceğiz

array([1.5 , 8.  , 1.25, 2.  ])

In [85]:
# tam tersi total ne kadardır onu da görebiliriz.
arr_orders.dot(arr_prices)

array([ 3.  , 20.5 , 10.  , 14.25])

Python'da Numpy'ın olmasının en temel sebebi matematiksel işlemler ve diğer kütüphanelere göre çok daha hızlı olması ve daha az yer kaplamasıdır.   
Numpy özellikle Pandas'ın temelini oluşturur. Pandas ise data analizde çok daha fazla kullanılan bir kütüphanedir.