In [1]:
%who 

Interactive namespace is empty.


In [1]:
import numpy as np

In [3]:
print('numpy: {}'.format(np.__version__))

numpy: 1.24.4


In [4]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\User\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\__init__.py'>
File:        c:\users\user\appdata\roaming\python\python38\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three grea

In [5]:
li_list = [1, 2.0, 3] 
li_list

[1, 2.0, 3]

In [6]:
type(li_list[1])

float

In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [8]:
['ali', 1]

['ali', 1]

In [9]:
np.array([1,'ali'])

array(['1', 'ali'], dtype='<U11')

In [10]:
np_array = np.array([1,2,3])

In [11]:
np_array.shape

(3,)

In [12]:
np_array.resize(5,3)

In [14]:
np_array.shape

(5, 3)

In [15]:
%who

li_list	 np	 np_array	 


In [16]:
arr_1D_int = np.array([1,2,3])
print(arr_1D_int.dtype)
print("Bytes:", arr_1D_int.itemsize)

arr_1D_float = np.array([1,2,3], dtype=np.float64)
print(arr_1D_float.dtype)
print("Bytes:", arr_1D_float.itemsize)

int32
Bytes: 4
float64
Bytes: 8


In [17]:
np.ones((3, 2), dtype=np.int64)

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [18]:
np.zeros((3, 2), dtype=np.int64)

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.repeat([1,2,3], 6)

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [23]:
np.linspace??

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Source:   
@array_function_dispatch(_linspace_dispatcher)
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `

In [25]:
np_lin = np.linspace(1,20,10)

In [28]:
np_lin.argmax??

Docstring:
a.argmax(axis=None, out=None, *, keepdims=False)

Return indices of the maximum values along the given axis.

Refer to `numpy.argmax` for full documentation.

See Also
--------
numpy.argmax : equivalent function
Type:      builtin_function_or_method


In [29]:
np_lin

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [30]:
np_lin.argmax()

9

In [31]:
a = np.arange(10)

In [32]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[::2]

array([0, 2, 4, 6, 8])

In [35]:
a[2]

2

In [36]:
a[0:2]

array([0, 1])

In [37]:
a[0:6:2]

array([0, 2, 4])

In [ ]:
hstack und vstack

In [45]:
npa_p = np.ones((2, 3), int)

In [48]:
np.ones??

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [40]:
2*npa_p

array([[2, 2, 2],
       [2, 2, 2]])

In [43]:
np.vstack([npa_p, 2.0*npa_p])

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [44]:
np.hstack([npa_p, 15*npa_p, 10*npa_p])

array([[ 1,  1,  1, 15, 15, 15, 10, 10, 10],
       [ 1,  1,  1, 15, 15, 15, 10, 10, 10]])

In [49]:
import sys

li_Demo = list(range(1000))
print(type(li_Demo))
print("Bytes:")
print(sys.getsizeof(1)*len(li_Demo))

print() 
print("Bytes:")
arr_Demo = np.arange(1000)
print(arr_Demo.size*arr_Demo.itemsize)

<class 'list'>
Bytes:
28000

Bytes:
4000


In [50]:

import time

c_Size = 10000000

li_1 = list(range(c_Size))
li_2 = list(range(c_Size))


arr_1 = np.arange(c_Size)
arr_2 = np.arange(c_Size)

start = time.time()


li_3 = [(x+y) for x,y in zip(li_1,li_2)]
print("Liste de toplam:", (time.time()-start)*1000, "ms")


start = time.time()

arr_3 = arr_1+arr_2
print("array de toplam:", (time.time()-start)*1000, "ms")

Liste de toplam: 6369.344472885132 ms
array de toplam: 411.8175506591797 ms


In [51]:
#matematiksel islemler koloay
arr_x = np.array([1,2,3])
arr_y = np.array([4,5,6])

print("x:", arr_x)
print("y:", arr_y)
print("x+y:", arr_x + arr_y) # toplam     [1 2 3] + [4 5 6] = [5  7  9]
print("x-y:", arr_x - arr_y) # cikarma    [1 2 3] - [4 5 6] = [-3 -3 -3]
print("x*y:", arr_x * arr_y) # carpma [1 2 3] * [4 5 6] = [4  10  18]
print("x/y:", arr_x / arr_y) # bölme       [1 2 3] / [4 5 6] = [0.25  0.4  0.5]
print("x^2:", arr_x**2)      # üst         [1 2 3] ^2 =  [1 4 9]   

x: [1 2 3]
y: [4 5 6]
x+y: [5 7 9]
x-y: [-3 -3 -3]
x*y: [ 4 10 18]
x/y: [0.25 0.4  0.5 ]
x^2: [1 4 9]


In [53]:
np.array([1,2,3]).ndim

1

In [57]:
np.array([[1,2,4], [1,2,3], [1,2,3]]).ndim

2

In [58]:
np.array([[[1,2,4]], [[1,2,3]]]).ndim

3

In [64]:
np.array([[[[1,2,4]]], [[[1,2,3]]]]).shape

(2, 1, 1, 3)

In [65]:
np.array([[[[1,2,4]]], [[[1,2,3]]]])

array([[[[1, 2, 4]]],


       [[[1, 2, 3]]]])

In [63]:
np.array([[1,2], [1,2], [1,2]]).shape

(3, 2)

In [66]:
np.array([[[1,2,4]], [[1,2,3]]]).shape

(2, 1, 3)

In [68]:
np.array([[[1,2,4]], [[1,2,3]]]).reshape(2,3).shape

(2, 3)

In [6]:
np_array_32 = np.array([[1,2], [1,2], [1,2]])

In [7]:
np_array_23 = np.array([[1,2], [1,2], [1,2]]).reshape(2,3)

In [8]:
np_array_32

array([[1, 2],
       [1, 2],
       [1, 2]])

In [9]:
np_array_23

array([[1, 2, 1],
       [2, 1, 2]])

In [10]:
np_array_32.ravel()

array([1, 2, 1, 2, 1, 2])

In [14]:
np_array_32.reshape(6,1)

array([[1],
       [2],
       [1],
       [2],
       [1],
       [2]])

In [16]:
np.sort(np_array_32.reshape(6,1), axis = 1)

array([[1],
       [2],
       [1],
       [2],
       [1],
       [2]])

In [17]:
np_array_32

array([[1, 2],
       [1, 2],
       [1, 2]])

In [20]:
np_array_32[1][0]

1

In [22]:
np_array_32 > 1

array([[False,  True],
       [False,  True],
       [False,  True]])

In [23]:
np_array_32 > 2

array([[False, False],
       [False, False],
       [False, False]])

In [25]:
np_array_32[np_array_32 > 1]

array([2, 2, 2])

In [26]:
arr_orders = np.array([
    [2, 0, 0, 0],
    [4, 1, 2, 2],
    [0, 1, 0, 1],
    [6, 0, 1, 2]
])
arr_totals = np.array([3, 20.50, 10, 14.25])
arr_prices = np.linalg.solve(arr_orders, arr_totals)
arr_prices

array([1.5 , 8.  , 1.25, 2.  ])

In [27]:
arr_orders.dot(arr_prices)

array([ 3.  , 20.5 , 10.  , 14.25])