In [2]:
import numpy as np
import pandas as pd

In [11]:
#kendi verimizi oluşturmak için: random 
veri1 = np.random.randint(1, 10, size = 5) #1'den 10'a kadar olan sayılardan rastgele sayı seçme
veri1

array([8, 9, 3, 9, 6])

In [9]:
populasyon = np.random.randint(1, 90,  20000) #1'le 90 yaş arasında 20000 kişi
populasyon

array([22, 66,  2, ..., 78, 24,  2])

In [10]:
#20000 kişiden 150 kişi seçme
populasyon[0 : 150]

array([22, 66,  2, 23, 23, 24, 12, 24, 28, 37, 17, 26, 62, 15, 59,  6, 76,
       78, 19, 67, 11, 61, 59, 11, 51, 12, 16,  6, 80, 82,  4, 85,  8, 64,
       35, 36, 38, 51, 37,  3, 21, 20, 86, 71,  5, 63, 63, 61, 17,  2, 37,
       86, 52, 36,  4, 69, 66, 76, 58, 54, 71, 11, 35, 27, 44, 58, 32,  6,
       73, 46, 30, 43, 50, 27, 50, 52, 13, 80, 53, 62, 70, 21, 32, 60, 32,
       25,  3, 51, 26, 12, 45, 77, 72, 65, 59, 40,  7, 39, 89, 67, 63, 66,
       63, 31, 74, 50, 42, 27, 70, 83, 27, 55,  3, 40, 33, 78, 65, 75, 11,
       54, 81, 51, 28, 15, 61, 78, 18, 29, 22, 80, 66, 71, 51, 48, 61, 25,
       26, 44, 87, 16, 21, 66, 83, 84, 88, 86, 31, 75, 37, 79])

In [12]:
#populasyonu değiştirdiğimde her seferinde veri değişiyor veri değişmesin diye sabitleme:
st = np.random.RandomState(1)
veri2 = st.choice(populasyon, 150)
veri2


array([66, 66, 17,  3, 35, 21, 47, 88, 43,  7, 44, 87, 20, 34, 47, 12, 41,
       46, 19, 35, 88, 71, 27,  7, 35, 23, 58, 56, 29, 24, 31, 25, 39, 74,
       43, 14, 62,  2, 73, 79, 15, 23, 79, 58, 21,  8, 37, 34, 68,  6, 13,
       80, 58,  9, 71, 20, 21, 27,  1, 76, 16, 67, 64, 73, 37, 44, 52, 64,
       52, 88,  7, 20, 10, 65, 12, 58, 71, 74, 82, 11, 81, 33, 83, 70, 30,
       15,  8,  1, 74, 73, 66, 76, 89, 16, 38, 15, 85, 88, 34,  5, 88, 88,
       48, 37, 31, 40, 27, 84, 78, 88, 82, 28, 64, 32, 73, 58, 71, 38, 50,
       64, 58,  1, 54, 35,  4,  2, 53, 40, 82,  8, 77, 17, 48, 85,  9, 14,
       11, 11, 36, 42, 82, 16, 70, 35, 67, 25, 60, 79, 73, 17])

In [16]:
#veri değişmesin diye sabitleme 2:
np.random.seed(1)
"random 1:" , np.random.choice(populasyon, 10)

('random 1:', array([66, 66, 17,  3, 35, 21, 47, 88, 43,  7]))

In [14]:
np.random.seed(2)
"random 2:" , np.random.choice(populasyon, 10)

('random 2:', array([13, 42, 46, 19, 73, 39, 62,  1, 85, 10]))

In [15]:
#ortalama
populasyon.mean()

44.94395

In [17]:
#ortalaması 44.94 olan populasyondan 15 kişi seçiyoruz
grup = np.random.choice(populasyon, 15)
grup

array([44, 87, 20, 34, 47, 12, 41, 46, 19, 35, 88, 71, 27,  7, 35])

In [18]:
#yukarıda seçtiğim grubun ortalaması
grup.mean()

40.86666666666667

In [19]:
#10 tane grup oluşturduk
grup1 = np.random.choice(populasyon, 15)
grup2 = np.random.choice(populasyon, 15)
grup3 = np.random.choice(populasyon, 15)
grup4 = np.random.choice(populasyon, 15)
grup5 = np.random.choice(populasyon, 15)
grup6 = np.random.choice(populasyon, 15)
grup7 = np.random.choice(populasyon, 15)
grup8 = np.random.choice(populasyon, 15)
grup9 = np.random.choice(populasyon, 15)
grup10 = np.random.choice(populasyon, 15)

In [20]:
#10 grubun ayrı ort.
grup1.mean(), grup2.mean(), grup3.mean(), grup4.mean(), grup5.mean(), grup6.mean(), grup7.mean(), grup8.mean(), grup9.mean(), grup10.mean()

(42.13333333333333,
 38.666666666666664,
 46.8,
 47.13333333333333,
 45.53333333333333,
 59.2,
 41.2,
 41.333333333333336,
 49.13333333333333,
 38.333333333333336)

In [23]:
#10 grubun toplam ort.
(grup1.mean() + grup2.mean() + grup3.mean() + grup4.mean() + grup5.mean() + grup6.mean() + grup7.mean() + grup8.mean() + grup9.mean() + grup10.mean())/10

44.94666666666666

In [24]:
#150 kişilik popülasyon seçip tahmin etseydik
grup11 = np.random.choice(populasyon, 150)

In [25]:
grup11.mean()

41.0

popülasyonda ne kadar çok bilgiye sahipseniz popülasyon hakkındaki tahminleriniz o kadar keskinleşecektir.
grupların sayısının fazla olması da tahmini keskinleşecektir. 

BETIMSEL ISTATISTIK

In [28]:
import seaborn

In [29]:
#hangi data setlerinin olduğunu görmek için
seaborn.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [30]:
#data setlerinden birini alıp yüklüyoruz
diamonds = seaborn.load_dataset("diamonds")

In [31]:
#yüklemiş olduk
diamonds

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [32]:
#ilk 5 tanesini görmek için
diamonds.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [33]:
#örnek görmek için (kaç tane)
diamonds.sample(8)

carat      cut color clarity  depth  table  price     x     y     z
24147   2.30    Ideal     J     SI1   62.3   57.0  12316  8.41  8.34  5.22
46214   0.64  Premium     D     SI2   62.8   54.0   1751  5.52  5.50  3.46
30361   0.36  Premium     H     VS2   60.0   62.0    729  4.62  4.58  2.76
3080    1.24    Ideal     J     SI1   62.3   57.0   3312  6.86  6.81  4.26
8032    1.00  Premium     F     SI2   61.6   62.0   4333  6.37  6.30  3.90
26271   2.15  Premium     G     SI2   58.9   58.0  15751  8.46  8.41  4.97
38244   0.32    Ideal     E      IF   62.9   54.0   1018  4.37  4.41  2.76
7725    0.26  Premium     E     VS1   61.9   58.0    580  4.11  4.10  2.54

In [34]:
#asıl veriyi bozmamak için kopya alıyoruz kopya üzerinde çalışıyoruz
df = diamonds.copy()

In [35]:
#veri elimize geldiğinde ilk info'suna (nasıl bir veri olduğuna) bakarız
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   carat    53940 non-null  float64 
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64 
 5   table    53940 non-null  float64 
 6   price    53940 non-null  int64   
 7   x        53940 non-null  float64 
 8   y        53940 non-null  float64 
 9   z        53940 non-null  float64 
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB


In [36]:
#ikinci olarak tanımlayıcı yada betimsel istatistik dediğimiz şeyi görmek için tanımlamak için
df.describe()

carat         depth         table         price             x  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184   3932.799722      5.731157   
std        0.474011      1.432621      2.234491   3989.439738      1.121761   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    950.000000      4.710000   
50%        0.700000     61.800000     57.000000   2401.000000      5.700000   
75%        1.040000     62.500000     59.000000   5324.250000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  53940.000000  53940.000000  
mean       5.734526      3.538734  
std        1.142135      0.705699  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  
max       58.900000     31.800000

In [37]:
#satırları sütun sütunları satır yapmak için
df.describe().T

count         mean          std    min     25%      50%      75%  \
carat  53940.0     0.797940     0.474011    0.2    0.40     0.70     1.04   
depth  53940.0    61.749405     1.432621   43.0   61.00    61.80    62.50   
table  53940.0    57.457184     2.234491   43.0   56.00    57.00    59.00   
price  53940.0  3932.799722  3989.439738  326.0  950.00  2401.00  5324.25   
x      53940.0     5.731157     1.121761    0.0    4.71     5.70     6.54   
y      53940.0     5.734526     1.142135    0.0    4.72     5.71     6.54   
z      53940.0     3.538734     0.705699    0.0    2.91     3.53     4.04   

            max  
carat      5.01  
depth     79.00  
table     95.00  
price  18823.00  
x         10.74  
y         58.90  
z         31.80

In [38]:
#yukarıda kategorik veriler yok onları görmek için ekliyoruz
df.describe(include = "all").T

count unique    top   freq         mean          std    min    25%  \
carat    53940.0    NaN    NaN    NaN      0.79794     0.474011    0.2    0.4   
cut        53940      5  Ideal  21551          NaN          NaN    NaN    NaN   
color      53940      7      G  11292          NaN          NaN    NaN    NaN   
clarity    53940      8    SI1  13065          NaN          NaN    NaN    NaN   
depth    53940.0    NaN    NaN    NaN    61.749405     1.432621   43.0   61.0   
table    53940.0    NaN    NaN    NaN    57.457184     2.234491   43.0   56.0   
price    53940.0    NaN    NaN    NaN  3932.799722  3989.439738  326.0  950.0   
x        53940.0    NaN    NaN    NaN     5.731157     1.121761    0.0   4.71   
y        53940.0    NaN    NaN    NaN     5.734526     1.142135    0.0   4.72   
z        53940.0    NaN    NaN    NaN     3.538734     0.705699    0.0   2.91   

            50%      75%      max  
carat       0.7     1.04     5.01  
cut         NaN      NaN      NaN  
color       NaN      NaN      NaN  
clarity     NaN      NaN      NaN  
depth      61.8     62.5     79.0  
table      57.0     59.0     95.0  
price    2401.0  5324.25  18823.0  
x           5.7     6.54    10.74  
y          5.71     6.54     58.9  
z          3.53     4.04     31.8

In [39]:
#değişkenlerin frekanslarını sayılarını görmek için
df.cut.value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [40]:
#hangi nicel değerden ne kadar olduğunu da görebiliriz(bu x için)
df.x.value_counts()

x
4.37     448
4.34     437
4.33     429
4.38     428
4.32     425
        ... 
10.74      1
9.36       1
8.89       1
10.23      1
10.00      1
Name: count, Length: 554, dtype: int64

describe ile aynı işlevi gören başka kütüphane install ediyoruz
RESEARCHPY

In [41]:
pip install researchpy


  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/f4/ce/be0b376ba6069f3f8ba240aa532a374733447453c93582d4c474effdde21/scipy-1.11.3-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     --------------------------- ------------ 41.0/60.4 kB ? eta -:--:--
     ---------------------------------------- 60.4/60.4 kB 1.1 MB/s eta 0:00:00
  Obtaining dependency information for statsmodels from https://files.pythonhosted.org/packages/a5/59/a4c19b49684ca2a469d7cd1a5682950e327c95c68e13aeea15533e576a8e/statsmodels-0.14.0-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/233.8 kB ? eta -:--:--
     ---------- ---------------------------- 61.4/233.8 kB 1.7 MB/s eta 0:00:01
     ------------------------ ------------- 153.6/233.8 kB 1.8 MB/s eta 0:00:01
     -------------------------------------- 233.8/233.8 kB 2.1 MB/s eta 0:00:00
   ------------------------------------


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [45]:
import researchpy as rp

summary_cont : Sayisal degiskenlerde
summary_cat = Kategorik degiskenlerde

In [54]:
import pandas as pd #(alttakini run'layamadığım için araştırıp bunu yaptım)
pd.DataFrame.iteritems = pd.DataFrame.items

In [56]:
rp.summary_cont(df[['carat' , 'depth' , 'price']])
#sayisal veriler, istatistiki degerlendirmeleri görecegiz, ort, standart sapma, güven aralıklarıyla ve standart hatayla ilgili bilgi verecek

c:\Users\ASUSVivaBook\AppData\Local\Programs\Python\Python312\Lib\site-packages\researchpy\summary.py:97: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'carat' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table_a.iloc[0,0] = ix
c:\Users\ASUSVivaBook\AppData\Local\Programs\Python\Python312\Lib\site-packages\researchpy\summary.py:97: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'depth' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  table_a.iloc[0,0] = ix
c:\Users\ASUSVivaBook\AppData\Local\Programs\Python\Python312\Lib\site-packages\researchpy\summary.py:97: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'price' has dtype incompatible with float64, please explicitly cast to a compatible dty

Variable        N       Mean         SD       SE  95% Conf.   Interval
0    carat  53940.0     0.7979     0.4740   0.0020     0.7939     0.8019
1    depth  53940.0    61.7494     1.4326   0.0062    61.7373    61.7615
2    price  53940.0  3932.7997  3989.4397  17.1774  3899.1320  3966.4675

In [61]:
rp.summary_cat(df[['cut', 'color', 'clarity']]) #çalıştıramadım 

KeyError: "['Outcome'] not in index"

CORALASYON
2 değişkenimizin arasındaki ilişkinin büyüklüğünü, yönünü veya pozitifse pozitifliğini negatifse negatifliğini gösterir. 

In [62]:
#korelasyonu alma
df[['carat', 'depth', 'price']].corr()

carat     depth     price
carat  1.000000  0.028224  0.921591
depth  0.028224  1.000000 -0.010647
price  0.921591 -0.010647  1.000000

GÜVEN ARALİĞİ
Ölçüm hassasiyetimizin göstergesi

100 kişi üzerinde yapılan bir çalışmada internette kalma süresi ortalama 240 saniyedir. 
n=100, ortalama=240, std=40
genel kabul %95 güven aralığında çalışmaktır. bunun dışındaki aralıklarda çalışırken yapmamız gereken z tablosuna bakmaktır.

güven aralığı belirlenir. 
%95, z=1.96
%99, z=2.58
HOCANIN GÖNDERDİĞİ DOSYADA FORMÜL VE HESAPLAMA VAR.


sonuç: yaklaşık olarak aralık değeri 232 ile 248 aralığı.
verisini aldığımız interneti kullanan kişilerin %95'i 232 ile 248 saniye arasında internette kalıyor.
verisini aldığımız interneti kullanan kişilerin %99'u 230 ile 250 saniye arasında internette kalıyor.

Satılacak bir ürün için alıcılara ne kadar ücret öderdiniz diye bir soru yöneltiliyor ve verdikleri cevaplar kaydediliyor. 
İstenen; bu ürün için optimum bir fiyat aralığı bulabilmek.

In [63]:
fiyatlar = np.random.randint(10, 110, 1000) #fiyatlar 10 ile 100 arasında 1000 kişiye soruldu.

In [65]:
fiyatlar.mean() #otalaması

58.438

z skoru tablosunu z skoru tablosu yada z skoru olasılık dağılımları yazarak bulabilirsin.

In [66]:
import statsmodels.stats.api as sms

In [68]:
#ürüne fiyat tahmin etmek için bu kod kullanılıyor.
sms.DescrStatsW(fiyatlar).tconfint_mean()

(56.6176295306756, 60.258370469324404)

sonuç: %95 güven aralığında baktığımızda bu ürüne verebileceğimiz fiyatı 56 ile 60 tl arasında belirlersek insanların %95'i ürünü alacaktır.