In [1]:
import numpy as np
import pandas as pd

# Örnek Teorisi

Bir ilçede 1 ile 90 yas arasinda 20000 kişi yaşıyor. Bu ilçede yaşayanların yaş ortalamasını öğrenmek istiyoruz.
Herkesin yaşını öğrenemeyeceğimizden dolayı rastgele seçeceğimiz 150 kişi ile ortalamayı bulmaya
çalışacağız.

### Örneklem çekme
Bunun için pek çok yöntem vardir. Burada random yöntemiyle örneklem çekilecektir.

In [2]:
veri1= np.random.randint(1, 10, size = 5)
veri1

array([3, 2, 2, 6, 6])

In [3]:
populasyon = np.random.randint(1, 90, 20000)

In [4]:
populasyon[0 : 10]

array([ 2, 14,  9, 37, 29, 78, 37, 21, 76, 83])

Random State

Random olarak oluşturulan bir veri setine her istediğimizde ulaşabilmemiz için oluşturulan bir çekirdektir.

In [5]:
# aşağıdaki gibi sabit bir liste oluşturuyor.
st = np.random.RandomState(0)
veri2 = st.choice(populasyon,10)
veri2

array([84, 43, 47, 52, 29, 51, 46, 88,  9, 46])

In [6]:
st = np.random.RandomState(0)
veri3 = st.choice(populasyon,150)
veri3

array([84, 43, 47, 52, 29, 51, 46, 88,  9, 46, 82, 64, 39, 39, 35, 15, 88,
       76, 10, 10,  8, 53, 11, 53, 18, 50,  6, 54,  3, 68, 51, 53,  9, 29,
       85, 47, 24, 30, 27, 13,  8, 87, 55, 46, 27, 71, 81, 76, 50, 79, 24,
       17, 70, 52, 41,  3, 17, 16, 51, 17, 45, 53, 72, 75, 83, 56, 64,  6,
       44, 52, 44, 88, 31,  7, 66, 88, 63,  8, 60, 85,  7,  8, 60, 86, 69,
       76, 37, 17, 19, 77, 50, 38, 33, 53, 75, 56, 37, 89, 89, 14, 84, 22,
       11, 39, 67,  7, 27, 40, 22, 27, 41, 57, 14,  3, 63, 88, 63, 17, 82,
       16, 34, 49, 22, 70, 88,  8, 79, 59,  5,  7, 88, 84, 50, 21, 55, 67,
       53, 55, 61, 13, 57, 34, 27, 14, 49, 84, 33, 51, 68, 27])

Random seed

- Makine öğrenmesi için önemli bir konu
- Yapılacak işlemlerin her tekrar edildiğinde aynı sonuçların elde edilmesini garanti eden bir işlem
- Örneğin örneklem çekilmesi için bir yapı oluşturduk, bir dahaki sefere örneklem çekme işlemini aynı yapıya göre yapabilmemizi sağlayacaktır.

In [7]:
# aşağıdaki gibi sabit bir liste oluşturuyor.
st = np.random.RandomState(10)
st.choice(populasyon,10)

array([ 8,  1, 79,  7, 38, 50, 10, 60, 71, 86])

In [8]:
np.random.seed(1) 
'random seed 1:',np.random.choice(populasyon,10)

('random seed 1:', array([63, 18, 43, 57, 85, 89, 58, 57, 65, 59]))

In [9]:
np.random.seed(2)
'random 2:',np.random.choice(populasyon,10)

('random 2:', array([21, 61, 11,  6, 14, 25,  8, 87, 39, 21]))

### Bir grup seçimi ve ortalaması

In [10]:
grup = np.random.choice(populasyon,10)

In [11]:
grup.mean()

39.2

In [12]:
veri3.mean()

45.43333333333333

### 10 grup seçimi ve bu 10 grubun ortalaması

In [13]:
grup1 = np.random.choice(populasyon,15)
grup2 = np.random.choice(populasyon,15)
grup3 = np.random.choice(populasyon,15)
grup4 = np.random.choice(populasyon,15)
grup5 = np.random.choice(populasyon,15)
grup6 = np.random.choice(populasyon,15)
grup7 = np.random.choice(populasyon,15)
grup8 = np.random.choice(populasyon,15)
grup9 = np.random.choice(populasyon,15)
grup10 = np.random.choice(populasyon,15)

In [14]:
grup1.mean(),grup2.mean(),grup3.mean(),grup4.mean(),grup5.mean(),grup6.mean(),grup7.mean(),grup8.mean(),grup8.mean(),grup10.mean()

(46.8,
 48.6,
 45.2,
 52.666666666666664,
 29.2,
 41.46666666666667,
 41.733333333333334,
 48.06666666666667,
 48.06666666666667,
 38.0)

In [15]:
(grup1.mean()+grup2.mean()+grup3.mean()+grup4.mean()+grup5.mean()+grup6.mean()+grup7.mean()+grup8.mean()+grup9.mean()+grup10.mean())/10

43.92

In [16]:
populasyon.mean()

44.91155

Bir örneklemde ortalama ... iken, örneklem olarak aldigimiz 10 grubun ortalamalarinın ortalaması ise merkezi limit teoremin gereğince populasyonun ortalamasına yaklasarak ... çıkmıştır.

# Betimsel İstatistik

# Seaborn Dataset 

In [17]:
import seaborn

In [18]:
seaborn.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

### Data Nasıl Yüklenir?

In [19]:
diamonds = seaborn.load_dataset('diamonds')

In [20]:
diamonds

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

### Data üzerinde çalışmaya başlamadan copy() ile kopyasını alıp onun üzerinde çalışmakta fayda var
### Yani orjinal veriye sonra ihtiyaç olabilir.

In [21]:
df = diamonds.copy()

In [22]:
df

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [23]:
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [24]:
df.sample(5)

carat      cut color clarity  depth  table  price     x     y     z
4444    0.92  Premium     H     SI1   62.0   60.0   3618  6.21  6.27  3.87
11802   1.00    Ideal     G     SI1   61.9   56.0   5088  6.45  6.37  3.97
10443   1.00  Premium     H     SI1   59.4   58.0   4788  6.51  6.46  3.85
9773    0.91    Ideal     I    VVS2   60.6   57.0   4663  6.25  6.27  3.79
33506   0.32    Ideal     F     VS2   62.5   56.0    828  4.40  4.37  2.74

In [25]:
df.tail()

carat        cut color clarity  depth  table  price     x     y     z
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

### Dataya Genel Bakış # data.info()

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype   
---  ------   --------------  -----   
 0   carat    53940 non-null  float64 
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64 
 5   table    53940 non-null  float64 
 6   price    53940 non-null  int64   
 7   x        53940 non-null  float64 
 8   y        53940 non-null  float64 
 9   z        53940 non-null  float64 
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB


### .describe() ile tanımlayıcı istatistiklere erişiyoruz

In [27]:
df.describe()

carat         depth         table         price             x  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184   3932.799722      5.731157   
std        0.474011      1.432621      2.234491   3989.439738      1.121761   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    950.000000      4.710000   
50%        0.700000     61.800000     57.000000   2401.000000      5.700000   
75%        1.040000     62.500000     59.000000   5324.250000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  53940.000000  53940.000000  
mean       5.734526      3.538734  
std        1.142135      0.705699  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  
max       58.900000     31.800000

### .describe().T # Buradaki T verinin traspozesini alıyor.

In [28]:
df.describe().T

count         mean          std    min     25%      50%      75%  \
carat  53940.0     0.797940     0.474011    0.2    0.40     0.70     1.04   
depth  53940.0    61.749405     1.432621   43.0   61.00    61.80    62.50   
table  53940.0    57.457184     2.234491   43.0   56.00    57.00    59.00   
price  53940.0  3932.799722  3989.439738  326.0  950.00  2401.00  5324.25   
x      53940.0     5.731157     1.121761    0.0    4.71     5.70     6.54   
y      53940.0     5.734526     1.142135    0.0    4.72     5.71     6.54   
z      53940.0     3.538734     0.705699    0.0    2.91     3.53     4.04   

            max  
carat      5.01  
depth     79.00  
table     95.00  
price  18823.00  
x         10.74  
y         58.90  
z         31.80

In [29]:
df.describe(include='all').T

count unique    top   freq         mean          std    min    25%  \
carat    53940.0    NaN    NaN    NaN      0.79794     0.474011    0.2    0.4   
cut        53940      5  Ideal  21551          NaN          NaN    NaN    NaN   
color      53940      7      G  11292          NaN          NaN    NaN    NaN   
clarity    53940      8    SI1  13065          NaN          NaN    NaN    NaN   
depth    53940.0    NaN    NaN    NaN    61.749405     1.432621   43.0   61.0   
table    53940.0    NaN    NaN    NaN    57.457184     2.234491   43.0   56.0   
price    53940.0    NaN    NaN    NaN  3932.799722  3989.439738  326.0  950.0   
x        53940.0    NaN    NaN    NaN     5.731157     1.121761    0.0   4.71   
y        53940.0    NaN    NaN    NaN     5.734526     1.142135    0.0   4.72   
z        53940.0    NaN    NaN    NaN     3.538734     0.705699    0.0   2.91   

            50%      75%      max  
carat       0.7     1.04     5.01  
cut         NaN      NaN      NaN  
color       NaN      NaN      NaN  
clarity     NaN      NaN      NaN  
depth      61.8     62.5     79.0  
table      57.0     59.0     95.0  
price    2401.0  5324.25  18823.0  
x           5.7     6.54    10.74  
y          5.71     6.54     58.9  
z          3.53     4.04     31.8

--------------------------------------------------------------------

In [35]:
df.cut = df.cut.astype(object)
df.color = df.color.astype(object)
df.clarity = df.clarity.astype(object)

In [36]:
df_object = df.select_dtypes(include=object)
df_object         # sadece object'de yazılabilir

cut color clarity
0          Ideal     E     SI2
1        Premium     E     SI1
2           Good     E     VS1
3        Premium     I     VS2
4           Good     J     SI2
...          ...   ...     ...
53935      Ideal     D     SI1
53936       Good     D     SI1
53937  Very Good     D     SI1
53938    Premium     H     SI2
53939      Ideal     D     SI2

[53940 rows x 3 columns]

In [37]:
df_object.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   cut      53940 non-null  object
 1   color    53940 non-null  object
 2   clarity  53940 non-null  object
dtypes: object(3)
memory usage: 1.2+ MB


In [38]:
df_object.describe()

cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

-----------------------------------------------------------

## .value_counts() değişkenin sınıflarını ve frekanslarını gösterir

In [39]:
df.cut.value_counts()

Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: cut, dtype: int64

-----------------------------------------------------------------

### Researchpy

### describe ile aynı işlevi gören researchpy'i install edip, import ediyoruz.

In [50]:
!pip install researchpy


In [51]:
import researchpy as rp

### summary_cont
- Sayısal değişkenler için betimleyici istatistikler veriyor
- Bu istatistiklere güven aralıklarını dahildir.

In [53]:
rp.summary_cont(df[['depth','table','x']]) 

Variable        N     Mean      SD      SE  95% Conf.  Interval
0    depth  53940.0  61.7494  1.4326  0.0062    61.7373   61.7615
1    table  53940.0  57.4572  2.2345  0.0096    57.4383   57.4760
2        x  53940.0   5.7312  1.1218  0.0048     5.7217    5.7406

Standart hata (SE), bir örneklemden elde edilen tahmini değerlerin popülasyonda bulunacak gerçek değer etrafındaki dağılımını ölçer .

### summary_cat
- Katagorik değişkenler için betimleyici istatistikleri verir
- Katogorik değişken sayılarını ve yüzdelerini verir.

In [54]:
rp.summary_cat(df[['cut','color','clarity']])

Variable    Outcome  Count  Percent
0       cut      Ideal  21551    39.95
1              Premium  13791    25.57
2            Very Good  12082    22.40
3                 Good   4906     9.10
4                 Fair   1610     2.98
5     color          G  11292    20.93
6                    E   9797    18.16
7                    F   9542    17.69
8                    H   8304    15.39
9                    D   6775    12.56
10                   I   5422    10.05
11                   J   2808     5.21
12  clarity        SI1  13065    24.22
13                 VS2  12258    22.73
14                 SI2   9194    17.04
15                 VS1   8171    15.15
16                VVS2   5066     9.39
17                VVS1   3655     6.78
18                  IF   1790     3.32
19                  I1    741     1.37

### coralasyon
coralasyon; iki değişken arasındaki ilişkinin büyüklüğü, yönü ile ilgilenir.

In [56]:
df[['depth','table','x']].corr()

depth     table         x
depth  1.000000 -0.295779 -0.025289
table -0.295779  1.000000  0.195344
x     -0.025289  0.195344  1.000000

# Güven aralığı
- Ölçüm hassasiyetinin bir göstergesidir.
- Belli bir olasılık yüzdesiyle ve bu yüzdeye bağlı olarak tahminlerin bir aralığını ifade eder.

### Güven aralığı için örnek
- Adım1: 100 kişi üzerinde yapılan bir çalışmada internette kalma süresi ortalama 240 saniyedir.       n=100, ortalama=240, std=40
   
- Adım2: Güven aralığı seçimi                                                                Yapılacak analizin %95 mi %99 mi güvenilirlikde olacağı belirlenir. Genel kabul %95 dir.             Z tablo değeri %95 için 1.96, %99 için 2.57 dir.
  
- Adım3: Güven aralığının hesabı
$$ort\frac{+}{}z\frac{std}{\sqrt{n}} =240\frac{+}{}1.96\frac{40}{\sqrt{100}}=240\frac{+}{}7.84$$

- Sonuç: Yaklasik 232 ile 248 aralığı. Yani İnternet kullanan kişilerin %95 i 232 ile 248 saniye arasında internette kaldığını söylemektedir.

$$ort\frac{+}{}z\frac{std}{\sqrt{n}} =240\frac{+}{}2.57\frac{40}{\sqrt{100}}=240\frac{+}{}10,28$$

- Sonuç: Yaklasik 230 ile 250 aralığı. Yani İnternet kullanan kişilerin %99 i 230 ile 250 saniye arasında internette kaldığını söylemektedir.

-------------------------------------------

### Güven aralığı uygulama: Fiyat stratejsi karar destek
Satılacak bir ürün için alıcılara ne kadar ücret öderdiniz diye bir soru yöneltiliyor ve verdikleri cevaplar kaydediliyor.
İstenen; bu ürün için optimum bir fiyat aralığı bulabilmek.

In [57]:
fiyatlar = np.random.randint(10,110,1000)

In [58]:
fiyatlar.mean()

59.172

In [59]:
import statsmodels.stats.api as sms

In [60]:
# %95 olasılıkla oluşturulan güven aralığı
sms.DescrStatsW(fiyatlar).tconfint_mean()

(57.360716965329836, 60.98328303467016)

### Sonuç:
Bu ürün için belirlenecek fiyat %95 güven ile 57 ile 61 aralığındadır. Yani alıcıların %95 i bu ürün için 57 ile 61 arasında bir fiyat ödeyeceğini söylemiştir.

------------------------------------------------------------------------------------------------